[package]
name = "rkyv_test"
version = "0.7.1"
authors = ["David Koloski <djkoloski@gmail.com>"]
edition = "2018"
description = "Test suite for rkyv crates"
license = "MIT"
repository = "https://github.com/rkyv/rkyv"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytecheck = { git = "https://github.com/cpunkzzz/bytecheck.git", rev = "b3cd049b38572fb9e9d6a0c0a08704457af884d4", optional = true, default-features = false }
ptr_meta = { version = "~0.1.3", default-features = false }
rkyv = { path = "../rkyv", default-features = false }
wasm-bindgen-test = { version = "0.3", optional = true }
ahash = { version = "0.7" }

[features]
default = ["std", "size_32", "validation"]
alloc = ["rkyv/alloc"]
arbitrary_enum_discriminant = ["rkyv/arbitrary_enum_discriminant"]
archive_be = ["rkyv/archive_be"]
archive_le = ["rkyv/archive_le"]
copy = ["rkyv/copy"]
copy_unsafe = ["rkyv/copy_unsafe"]
rend = ["rkyv/rend"]
size_16 = ["rkyv/size_16"]
size_32 = ["rkyv/size_32"]
size_64 = ["rkyv/size_64"]
std = ["alloc", "bytecheck/std", "rkyv/std"]
strict = ["rkyv/strict"]
validation = ["alloc", "bytecheck", "rkyv/validation"]
wasm = ["wasm-bindgen-test"]
